# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  GOOGLE_CLIENT_ID: 470822917737-0i7tcdc3fojdtdg9hed62fnhibfdnupp.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: FKr6cFizNp_nRreH4GGdZTQQ

  FACEBOOK_KEY: 1031917320164249
  FACEBOOK_SECRET: a1b5806d7ff9f37fd2e77a42d9f8ce51
