# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5efc9f606ed719eb0d61873daf8541ba9a92f368a155220391bb13daeaee6ea48689ab4592c50e6f42e713ddf2e00157f0e265e46362efce6270c0ec7ebe5135

test:
  secret_key_base: 9bc1c27137df9999a4ef1eab4ecc10daf38aac5f0daae336a8f6b7e579d09ed3c1b2491e981fedad212aea6f6a91ca531406738ed45954698699347b9a821677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
