production:
  solr:
    hostname: localhost
    port: 8983 #tomcat defaults to port 8080
    #path: '/solr-example'
    log_level: WARNING
    #pid_dir: '/var/run'

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    pid_dir: defaults to 'app/solr/pids/development'
    rm -rf solr/test/bind_address: defaults to '0.0.0.0' which binds to every interface
  disabled: false # note that this is not indented within `solr`

staging:
  solr:
    hostname: localhost
    port: 8981
    #path: '/solr-example'
    log_level: WARNING
    #pid_dir: '/var/run'
